<?php
declare(strict_types=1);

// BranchDataSubjectRequest SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BranchDataSubjectRequestUtility::setRegistrar(function (BranchDataSubjectRequestUtility $u): void {
    $u->clean = [BranchDataSubjectRequestClean::class, 'call'];
    $u->done = [BranchDataSubjectRequestDone::class, 'call'];
    $u->make_error = [BranchDataSubjectRequestMakeError::class, 'call'];
    $u->feature_add = [BranchDataSubjectRequestFeatureAdd::class, 'call'];
    $u->feature_hook = [BranchDataSubjectRequestFeatureHook::class, 'call'];
    $u->feature_init = [BranchDataSubjectRequestFeatureInit::class, 'call'];
    $u->fetcher = [BranchDataSubjectRequestFetcher::class, 'call'];
    $u->make_fetch_def = [BranchDataSubjectRequestMakeFetchDef::class, 'call'];
    $u->make_context = [BranchDataSubjectRequestMakeContext::class, 'call'];
    $u->make_options = [BranchDataSubjectRequestMakeOptions::class, 'call'];
    $u->make_request = [BranchDataSubjectRequestMakeRequest::class, 'call'];
    $u->make_response = [BranchDataSubjectRequestMakeResponse::class, 'call'];
    $u->make_result = [BranchDataSubjectRequestMakeResult::class, 'call'];
    $u->make_point = [BranchDataSubjectRequestMakePoint::class, 'call'];
    $u->make_spec = [BranchDataSubjectRequestMakeSpec::class, 'call'];
    $u->make_url = [BranchDataSubjectRequestMakeUrl::class, 'call'];
    $u->param = [BranchDataSubjectRequestParam::class, 'call'];
    $u->prepare_auth = [BranchDataSubjectRequestPrepareAuth::class, 'call'];
    $u->prepare_body = [BranchDataSubjectRequestPrepareBody::class, 'call'];
    $u->prepare_headers = [BranchDataSubjectRequestPrepareHeaders::class, 'call'];
    $u->prepare_method = [BranchDataSubjectRequestPrepareMethod::class, 'call'];
    $u->prepare_params = [BranchDataSubjectRequestPrepareParams::class, 'call'];
    $u->prepare_path = [BranchDataSubjectRequestPreparePath::class, 'call'];
    $u->prepare_query = [BranchDataSubjectRequestPrepareQuery::class, 'call'];
    $u->graphql_body = [BranchDataSubjectRequestGraphql::class, 'body'];
    $u->graphql_errors = [BranchDataSubjectRequestGraphql::class, 'errors'];
    $u->result_basic = [BranchDataSubjectRequestResultBasic::class, 'call'];
    $u->result_body = [BranchDataSubjectRequestResultBody::class, 'call'];
    $u->result_headers = [BranchDataSubjectRequestResultHeaders::class, 'call'];
    $u->transform_request = [BranchDataSubjectRequestTransformRequest::class, 'call'];
    $u->transform_response = [BranchDataSubjectRequestTransformResponse::class, 'call'];
});
